export const coursesData = [
    // Frontend Courses
    { title: 'HTML5 Semántico y Accesibilidad Web' },
    { title: 'CSS3 Avanzado y Flexbox/Grid' },
    { title: 'JavaScript ES6+ Fundamentals' },
    { title: 'TypeScript para Desarrollo Web' },
    { title: 'React.js - Hooks y Context API' },
    { title: 'Vue.js 3 - Composition API' },
    { title: 'Angular 18 - Signals y Control Flow' },
    { title: 'Next.js - Full Stack React Framework' },
    { title: 'Svelte y SvelteKit' },
    { title: 'Tailwind CSS - Utility-First Framework' },
    { title: 'Webpack y Vite - Module Bundlers' },
    { title: 'Testing Frontend con Jest y Cypress' },
    { title: 'PWA - Progressive Web Apps' },
    { title: 'Micro-frontends con Module Federation' },
    { title: 'Web Performance Optimization' },

    // Backend Courses
    { title: 'Node.js - APIs REST con Express' },
    { title: 'Python Django - Framework Web' },
    { title: 'FastAPI - APIs modernas con Python' },
    { title: 'Java Spring Boot - Microservicios' },
    { title: 'C# .NET Core - Web APIs' },
    { title: 'Go - Desarrollo de APIs Concurrentes' },
    { title: 'Rust - Sistemas de Alto Rendimiento' },
    { title: 'GraphQL con Apollo Server' },
    { title: 'Bases de Datos PostgreSQL Avanzado' },
    { title: 'MongoDB - Base de Datos NoSQL' },
    { title: 'Redis - Cache y Session Store' },
    { title: 'Docker - Containerización de Aplicaciones' },
    { title: 'Kubernetes - Orquestación de Contenedores' },
    { title: 'Microservicios - Arquitectura Distribuida' },
    { title: 'Event-Driven Architecture con RabbitMQ' },

    // Infrastructure as Code (IaC)
    { title: 'Terraform - Infraestructura como Código' },
    { title: 'Ansible - Automatización de Configuraciones' },
    { title: 'Pulumi - IaC con Lenguajes de Programación' },
    { title: 'AWS CloudFormation - Templates' },
    { title: 'Azure ARM Templates' },
    { title: 'Google Cloud Deployment Manager' },
    { title: 'Helm Charts para Kubernetes' },
    { title: 'GitOps con ArgoCD y Flux' },
    { title: 'Vagrant - Ambientes de Desarrollo' },
    { title: 'Packer - Automatización de Imágenes' },
    { title: 'Chef - Configuration Management' },
    { title: 'Puppet - Infrastructure Automation' },
    { title: 'SaltStack - Remote Execution' },
    { title: 'Crossplane - Cloud Native IaC' },
    { title: 'CDK - Cloud Development Kit' },

    // Cloud Courses
    { title: 'AWS Solutions Architect Associate' },
    { title: 'Azure Fundamentals AZ-900' },
    { title: 'Google Cloud Platform - Core Services' },
    { title: 'AWS Lambda - Serverless Computing' },
    { title: 'Azure Functions - Event-Driven Computing' },
    { title: 'Google Cloud Functions' },
    { title: 'AWS EKS - Kubernetes en la Nube' },
    { title: 'Azure Kubernetes Service (AKS)' },
    { title: 'Google Kubernetes Engine (GKE)' },
    { title: 'Multi-Cloud Strategy y Hybrid Cloud' },
    { title: 'Cloud Security Best Practices' },
    { title: 'Cloud Cost Optimization' },
    { title: 'Monitoring y Observabilidad en Cloud' },
    { title: 'Disaster Recovery en la Nube' },
    { title: 'Cloud Native Architecture Patterns' }
];